JobTracker/Models/Opening.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace JobTracker.Models
{
    public class Opening
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Company { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }
        [Display(Name = "Date Applied")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DateApplied { get; set; }
        [Display(Name = "Interest Level")]
        public int InterestLevel { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Note> Notes { get; set; }
        public virtual ICollection<Todo> Todos { get; set; }
    }
}

JobTracker/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobTracker.Models;
using JobTracker.DAL;

namespace JobTracker.Controllers
{
    public class ContactController : Controller
    {
        private JobTrackerContext db = new JobTrackerContext();

        // GET: /Contact/
        public ActionResult Index()
        {
            return View(db.Contacts.ToList());
        }

        // GET: /Contact/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contacts.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // GET: /Contact/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Contact/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,Name,JobTitle,Company,Phone,Email")] Contact contact)
        {
            if (ModelState.IsValid)
            {
                db.Contacts.Add(contact);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(contact);
        }

        // GET: /Contact/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contacts.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // POST: /Contact/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,Name,JobTitle,Company,Phone,Email")] Contact contact)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contact).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(contact);
        }

        // GET: /Contact/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contacts.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // POST: /Contact/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Contact contact = db.Contacts.Find(id);
            db.Contacts.Remove(contact);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobTracker/Controllers/OpeningController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobTracker.Models;
using JobTracker.DAL;
using JobTracker.ViewModels;

namespace JobTracker.Controllers
{
    public class OpeningController : Controller
    {
        private JobTrackerContext db = new JobTrackerContext();

        // GET: /Opening/
        public ActionResult Index()
        {
            return View(db.Openings.ToList());
        }

        // GET: /Opening/Details/5
        public ActionResult Details(int? id)
        {
            var viewModel = new OpeningDetailsData();
            var openings = db.Openings
                .Include(x => x.Contacts)
                .Include(x => x.Notes)
                .Include(x => x.Todos);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Opening opening = db.Openings.Find(id);
            if (opening == null)
            {
                return HttpNotFound();
            }

            if (id != null)
            {
                ViewBag.OpeningID = id.Value;
                viewModel.Opening = opening;
                viewModel.Contacts = openings.Where(x => x.ID == id.Value).Single().Contacts;
                viewModel.Notes = openings.Where(x => x.ID == id.Value).Single().Notes;
                viewModel.Todos = openings.Where(x => x.ID == id.Value).Single().Todos; 
            }

            return View(viewModel);
        }

        // GET: /Opening/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Opening/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Title,Company,Url,Description,DateApplied,InterestLevel")] Opening opening)
        {
            if (ModelState.IsValid)
            {
                db.Openings.Add(opening);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(opening);
        }

        // GET: /Opening/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Opening opening = db.Openings.Find(id);
            if (opening == null)
            {
                return HttpNotFound();
            }
            return View(opening);
        }

        // POST: /Opening/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Title,Company,Url,Description,DateApplied,InterestLevel")] Opening opening)
        {
            if (ModelState.IsValid)
            {
                db.Entry(opening).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(opening);
        }

        // GET: /Opening/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Opening opening = db.Openings.Find(id);
            if (opening == null)
            {
                return HttpNotFound();
            }
            return View(opening);
        }

        // POST: /Opening/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Opening opening = db.Openings.Find(id);
            db.Openings.Remove(opening);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobTracker/Views/Opening/Create.cshtml
@model JobTracker.Models.Opening

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Opening</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Company, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Company)
                @Html.ValidationMessageFor(model => model.Company)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Url, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url)
                @Html.ValidationMessageFor(model => model.Url)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateApplied, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateApplied)
                @Html.ValidationMessageFor(model => model.DateApplied)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InterestLevel, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InterestLevel)
                @Html.ValidationMessageFor(model => model.InterestLevel)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JobTracker/Views/Opening/Delete.cshtml
@model JobTracker.Models.Opening

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Opening</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateApplied)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateApplied)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InterestLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InterestLevel)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

JobTracker/Views/Opening/Details.cshtml
@model JobTracker.ViewModels.OpeningDetailsData

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Opening</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Opening.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opening.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Opening.Company)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opening.Company)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Opening.Url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opening.Url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Opening.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opening.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Opening.DateApplied)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opening.DateApplied)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Opening.InterestLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opening.InterestLevel)
        </dd>

    </dl>
</div>

@if (Model.Contacts != null)
{
    <h4>Contacts</h4>

    <p>
        @Html.ActionLink("Create New Contact", "Create", "Contact")
    </p>
    <table class="table">
        <tr>
            <th>
                Name
            </th>
            <th>
                Job Title
            </th>
            <th>
                Company
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Contacts)
        {
        <tr>
            <td>
                @item.Name
            </td>
            <td>
                @item.JobTitle
            </td>
            <td>
                @item.Company
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "Contact", new { id = item.ID }, null) |
                @Html.ActionLink("Details", "Details", "Contact", new { id = item.ID }, null) |
                @Html.ActionLink("Delete", "Delete", "Contact", new { id = item.ID }, null)
            </td>
        </tr>
        }
    </table>
}

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Opening.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

JobTracker/Views/Opening/Edit.cshtml
@model JobTracker.Models.Opening

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Opening</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Company, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Company)
                @Html.ValidationMessageFor(model => model.Company)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Url, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url)
                @Html.ValidationMessageFor(model => model.Url)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateApplied, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateApplied)
                @Html.ValidationMessageFor(model => model.DateApplied)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InterestLevel, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InterestLevel)
                @Html.ValidationMessageFor(model => model.InterestLevel)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JobTracker/Views/Opening/Index.cshtml
@model IEnumerable<JobTracker.Models.Opening>

@{
    ViewBag.Title = "Openings";
}

<h2>Openings</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Company)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateApplied)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Company)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateApplied)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>